import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import MainLayout from '../src/layout/MainLayout'
import useUserToken from "../hooks/useUserToken"
import { useRouter } from 'next/router'
import Button from '../src/layout/components/Button'

const Home: NextPage = () => {
  const router = useRouter()
  const [token] = useUserToken()
  if(token)router.push("/tickets")
  return (
    <div className='h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout height='h-[92%]'>
        <div className='h-full flex flex-col justify-center items-center gap-4 md:px-[100px]'>
          <Link href="/login">
            <Button title='ورود' className='w-full py-2 md:py-4'/>
          </Link>
          <Link href={"/register"}>
            <Button title='ثبت نام' className='w-full py-2 md:py-4'/>
          </Link>
        </div>
      </MainLayout>
    </div>
  )
}



export default Home
