import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import MainLayout from '../src/layout/MainLayout'
import styles from '../styles/Home.module.css'
import useUserToken from "../hooks/useUserToken"
import { useRouter } from 'next/router'
import { server } from '../config/server'
import axios from 'axios'

const Home: NextPage = () => {
  const router = useRouter()
  const [token] = useUserToken()
  if(token)router.push("/tickets")
  return (
    <div className='h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout height='h-[92%]'>
        <div className='h-full flex flex-col justify-center items-center gap-4'>
          <Link href="/login">
            <button  className='bg-[#2352C3] w-full py-2 rounded-lg'>ورود</button>
          </Link>
          <Link href={"/register"}>
            <button className='bg-[#2352C3] w-full py-2 rounded-lg'>ثبت نام</button>
          </Link>
        </div>
      </MainLayout>
    </div>
  )
}



export default Home
